# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.14.0_rc3

inherit perl-module

DESCRIPTION="A Template plugin to use DateTime objects"
HOMEPAGE="http://search.cpan.org/dist/${PN}/"
SRC_URI="mirror://cpan/authors/id/D/DM/DMAKI/${P}.tar.gz"
LICENSE="|| ( Artistic GPL-2 )"

SLOT="0"
KEYWORDS="amd64 x86"
RESTRICT="nomirror"
SRC_TEST="do"

IUSE="test"
RDEPEND="dev-lang/perl
	dev-perl/DateTime
	dev-perl/Template-Toolkit
	dev-perl/DateTime-Format-Strptime"
DEPEND="${RDEPEND}
	test? ( virtual/perl-Test-Simple )"
